global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'products-service'
    static_configs:
      - targets: ['products-service:5002']
    metrics_path: '/metrics'
    scrape_interval: 5s